
import Project.ConnectionProvider;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
    }
    
    DefaultTableModel model = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRoomCost = new javax.swing.JTextField();
        txtFoodNo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtCash = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        cmbPayM = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtFoodName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtRoomNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        cmbCash1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtTotal1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCash1 = new javax.swing.JTextField();
        txtBalance1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txtFoodNo1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtFoodName1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtQty1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Food Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 136, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Qty");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 136, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Room Cost");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 75, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Total");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 354, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Cash");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 381, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Balance");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 410, -1, -1));

        txtRoomCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRoomCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRoomCostKeyPressed(evt);
            }
        });
        jPanel1.add(txtRoomCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 72, 120, -1));

        txtFoodNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFoodNo.setForeground(new java.awt.Color(0, 0, 153));
        txtFoodNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFoodNoKeyReleased(evt);
            }
        });
        jPanel1.add(txtFoodNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 156, 81, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 460, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 0, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 450, 12));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Unit Price", "Qty", "Sub Total"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 194, 436, 139));

        txtCash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCashKeyPressed(evt);
            }
        });
        jPanel1.add(txtCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 378, 115, -1));

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 351, 115, -1));

        txtBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 407, 115, -1));

        cmbPayM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbPayM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Credit Card", "Debit Card", "Check" }));
        jPanel1.add(cmbPayM, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 351, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Payment Method");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 354, -1, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Internal Customer");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 27, -1, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        jButton9.setText("Print");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 460, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        txtFoodName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFoodName.setForeground(new java.awt.Color(0, 0, 153));
        txtFoodName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFoodNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtFoodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 156, 181, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Food No");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 136, -1, -1));

        txtQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtQty.setForeground(new java.awt.Color(0, 0, 153));
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 156, 34, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Price");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 136, -1, -1));

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(0, 0, 153));
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 156, 107, -1));

        txtRoomNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRoomNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRoomNoKeyPressed(evt);
            }
        });
        jPanel1.add(txtRoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 72, 120, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Room No");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 75, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 450, 12));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 470, 510));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Unit Price", "Qty", "Sub Total"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 441, 136));

        cmbCash1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbCash1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Credit Card", "Debit Card", "Check" }));
        jPanel2.add(cmbCash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 352, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Payment Method");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 355, -1, -1));

        txtTotal1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 115, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Total");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Cash");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 382, -1, -1));

        txtCash1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCash1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCash1KeyPressed(evt);
            }
        });
        jPanel2.add(txtCash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 115, -1));

        txtBalance1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtBalance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 115, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Balance");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png"))); // NOI18N
        jButton6.setText("Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 460, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        jButton8.setText("Print");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 460, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 0, 51));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, 450, 10));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("External Customer");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 25, -1, -1));

        txtFoodNo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFoodNo1.setForeground(new java.awt.Color(0, 0, 153));
        txtFoodNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFoodNo1ActionPerformed(evt);
            }
        });
        txtFoodNo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFoodNo1KeyReleased(evt);
            }
        });
        jPanel2.add(txtFoodNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 156, 81, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Food No");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 136, -1, -1));

        txtFoodName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFoodName1.setForeground(new java.awt.Color(0, 0, 153));
        txtFoodName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFoodName1KeyReleased(evt);
            }
        });
        jPanel2.add(txtFoodName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 156, 181, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Food Name");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 136, -1, -1));

        txtQty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtQty1.setForeground(new java.awt.Color(0, 0, 153));
        txtQty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQty1ActionPerformed(evt);
            }
        });
        txtQty1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQty1KeyReleased(evt);
            }
        });
        jPanel2.add(txtQty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 156, 34, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Qty");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 136, -1, -1));

        txtPrice1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrice1.setForeground(new java.awt.Color(0, 0, 153));
        txtPrice1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrice1KeyReleased(evt);
            }
        });
        jPanel2.add(txtPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 156, 107, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Price");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 136, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 480, 510));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SBG.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFoodNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFoodNoKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String foodCode = txtFoodNo.getText();
            
            try{
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                ResultSet rs1=st.executeQuery("select * from food where food_id='"+foodCode+"'");
                
                if(rs1.next()==false){
                    JOptionPane.showMessageDialog(this, "Food number is invalied!");
                }
                else{
                    String foodName = rs1.getString("food_name");
                    String price = rs1.getString("price");
                    
                    txtFoodName.setText(foodName.trim());
                    txtPrice.setText(price.trim());
                    
                    txtQty.requestFocus();
                }
            }
            catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_txtFoodNoKeyReleased

    private void txtFoodNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFoodNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoodNameKeyReleased

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            int price = Integer.parseInt(txtPrice.getText());
            int qty = Integer.parseInt(txtQty.getText());

            int tot = price * qty;

            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {
                   /*
                    txtFoodName.getText(),
                    txtPrice.getText(),
                    txtQty.getText
                    */
                    txtFoodName.getText(),
                    price,
                    qty,
                    tot
                });
            
           int finalTot =0;
                for(int i=0;i< jTable1.getRowCount();i++){
                    finalTot = finalTot + Integer.parseInt(jTable1.getValueAt(i,3).toString());
                }
                txtTotal.setText(String.valueOf(finalTot));
                txtFoodNo.setText("");
                txtFoodName.setText("");
                txtPrice.setText("");
                txtQty.setText("");
                txtFoodNo.requestFocus();
            }
    }//GEN-LAST:event_txtQtyKeyReleased

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        model.removeRow(jTable1.getSelectedRow());
        
        int finalTot =0;
        for(int i=0;i< jTable1.getRowCount();i++){
            finalTot = finalTot + Integer.parseInt(jTable1.getValueAt(i,3).toString());
        }
        txtTotal.setText(String.valueOf(finalTot));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
       try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","");
            
            JasperDesign jdesDesign = JRXmlLoader.load("src\\report1.jrxml");

            String query = "SELECT bill.`total` AS bill_total, bill.`pay_method` AS bill_pay_method, bill.`cash` AS bill_cash, bill.`balance` AS bill_balance, bill_body.`name` AS bill_body_name, bill_body.`unit_price` AS bill_body_unit_price, bill_body.`qty` AS bill_body_qty, bill_body.`sub_tot` AS bill_body_sub_tot FROM `bill` bill, `bill_body` bill_body";
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);

            jdesDesign.setQuery(updateQuery);

            JasperReport jrepoReport = JasperCompileManager.compileReport(jdesDesign);
            JasperPrint jprint = JasperFillManager.fillReport(jrepoReport, null,con);

            JasperViewer.viewReport(jprint,false);
            /*
            JasperDesign jdesign = JRXmlLoader.load("E:\\Java Projects\\Hotel_Manager\\src\\reportBill_internal.jrxml");
            JasperReport ireport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(ireport, null,)*/
            
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }   
       
       
       //CLEAR TABLE
       try
            {
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                Statement st1=con.createStatement();
                st.executeUpdate("delete from bill_body");
                st1.executeUpdate("delete from bill");
                
 
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Connection Error");
            }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtRoomCostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRoomCostKeyPressed
        // TODO add your handling code here:
        //room cost
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String roomCost = txtRoomCost.getText();
            
            model = (DefaultTableModel)jTable1.getModel();

            model.addRow(new Object[]
                {
                    "Room Cost",
                    "",
                    "",
                    roomCost,
                });
           
        }
    }//GEN-LAST:event_txtRoomCostKeyPressed

    private void txtRoomNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRoomNoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomNoKeyPressed

    private void txtCashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int pay = Integer.parseInt(txtTotal.getText());
            int cash = Integer.parseInt(txtCash.getText());
        
        int bal = cash - pay;
        txtBalance.setText(String.valueOf(bal));
        
        //Update room availability
        String roomNo =txtRoomNo.getText();
        
        String available="Booked";
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            
            ResultSet rs1=st.executeQuery("select * from room where room_id = '"+roomNo+"' and available='"+available+"' ");
            if(rs1.next()){
            PreparedStatement ps=con.prepareStatement("update room set available=? where room_id='"+roomNo+"'");
            ps.setString(1,"Available");
            ps.executeUpdate();

            }
            else{
                JFrame jf=new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf, "This Room No is not booked!");
            }
        }
        catch(Exception e){
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Connection Error");
        }
        
        
        int total =Integer.parseInt(txtTotal.getText());
        String paymethod =cmbPayM.getSelectedItem().toString();
        //int cash =Integer.parseInt(txtCash.getText());
        int balance =Integer.parseInt(txtBalance.getText());
        
        try
        {
            Connection con=ConnectionProvider.getCon();
            PreparedStatement ps=con.prepareStatement("insert into bill value(?,?,?,?)");
            ps.setInt(1, total);
            ps.setString(2, paymethod);
            ps.setInt(3, cash);
            ps.setInt(4, balance);
            ps.executeUpdate();
            
                PreparedStatement ps1=con.prepareStatement("insert into bill_body value(?,?,?,?)");
                
                for(int i=0; i<jTable1.getRowCount(); i++){
                  
                    String name =(String)jTable1.getValueAt(i,0).toString();
                    String unit =(String)jTable1.getValueAt(i, 1).toString();
                    String qty =(String)jTable1.getValueAt(i, 2).toString();
                    String subtot =(String)jTable1.getValueAt(i, 3).toString();
                    
                    ps1.setString(1,name);
                    ps1.setString(2,unit);
                    ps1.setString(3,qty);
                    ps1.setString(4,subtot);
                    ps1.addBatch();
                }
                ps1.executeBatch();
                //ps1.executeUpdate();
            
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Successfully!");
            
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showConfirmDialog(jf,e);
        }
        
        }
        
        
        
    }//GEN-LAST:event_txtCashKeyPressed

    private void txtFoodNo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFoodNo1KeyReleased
        // TODO add your handling code here
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String foodCode = txtFoodNo1.getText();
            
            try{
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                ResultSet rs1=st.executeQuery("select * from food where food_id='"+foodCode+"'");
                
                if(rs1.next()==false){
                    JOptionPane.showMessageDialog(this, "Food number is invalied!");
                }
                else{
                    String foodName = rs1.getString("food_name");
                    String price = rs1.getString("price");
                    
                    txtFoodName1.setText(foodName.trim());
                    txtPrice1.setText(price.trim());
                    
                    txtQty1.requestFocus();
                }
            }
            catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_txtFoodNo1KeyReleased

    private void txtFoodName1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFoodName1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoodName1KeyReleased

    private void txtQty1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQty1KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            int price = Integer.parseInt(txtPrice1.getText());
            int qty = Integer.parseInt(txtQty1.getText());

            int tot = price * qty;

            model = (DefaultTableModel)jTable2.getModel();

            model.addRow(new Object[]
                {
                    txtFoodName1.getText(),
                    txtPrice1.getText(),
                    txtQty1.getText(),
                    tot
                });
            
           int finalTot =0;
                for(int i=0;i< jTable2.getRowCount();i++){
                    finalTot = finalTot + Integer.parseInt(jTable2.getValueAt(i,3).toString());
                }
                txtTotal1.setText(String.valueOf(finalTot));
                txtFoodNo1.setText("");
                txtFoodName1.setText("");
                txtPrice1.setText("");
                txtQty1.setText("");
                txtFoodNo1.requestFocus();
            }
    }//GEN-LAST:event_txtQty1KeyReleased

    private void txtPrice1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrice1KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPrice1KeyReleased

    private void txtQty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQty1ActionPerformed

    
    
    
    
    private void txtCash1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCash1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int pay = Integer.parseInt(txtTotal1.getText());
            int cash = Integer.parseInt(txtCash1.getText());
        
        int bal = cash - pay;
        txtBalance1.setText(String.valueOf(bal));
        
         
        int total =Integer.parseInt(txtTotal1.getText());
        String paymethod =cmbCash1.getSelectedItem().toString();
        //int cash =Integer.parseInt(txtCash.getText());
        int balance =Integer.parseInt(txtBalance1.getText());
        
        try
        {
            Connection con=ConnectionProvider.getCon();
            PreparedStatement ps=con.prepareStatement("insert into bill value(?,?,?,?)");
            ps.setInt(1, total);
            ps.setString(2, paymethod);
            ps.setInt(3, cash);
            ps.setInt(4, balance);
            ps.executeUpdate();
            
                PreparedStatement ps1=con.prepareStatement("insert into bill_body value(?,?,?,?)");
                
                for(int i=0; i<jTable2.getRowCount(); i++){
                  
                    String name =(String)jTable2.getValueAt(i,0).toString();
                    String unit =(String)jTable2.getValueAt(i, 1).toString();
                    String qty =(String)jTable2.getValueAt(i, 2).toString();
                    String subtot =(String)jTable2.getValueAt(i, 3).toString();
                    
                    ps1.setString(1,name);
                    ps1.setString(2,unit);
                    ps1.setString(3,qty);
                    ps1.setString(4,subtot);
                    ps1.addBatch();
                }
                ps1.executeBatch();
                //ps1.executeUpdate();
            
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"Successfully!");
            
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showConfirmDialog(jf,e);
        }
        
        }
    }//GEN-LAST:event_txtCash1KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        model.removeRow(jTable2.getSelectedRow());
        
        int finalTot =0;
        for(int i=0;i< jTable2.getRowCount();i++){
            finalTot = finalTot + Integer.parseInt(jTable2.getValueAt(i,3).toString());
        }
        txtTotal1.setText(String.valueOf(finalTot));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","");
            
            JasperDesign jdesDesign = JRXmlLoader.load("src\\report1.jrxml");

            String query = "SELECT bill.`total` AS bill_total, bill.`pay_method` AS bill_pay_method, bill.`cash` AS bill_cash, bill.`balance` AS bill_balance, bill_body.`name` AS bill_body_name, bill_body.`unit_price` AS bill_body_unit_price, bill_body.`qty` AS bill_body_qty, bill_body.`sub_tot` AS bill_body_sub_tot FROM `bill` bill, `bill_body` bill_body";
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);

            jdesDesign.setQuery(updateQuery);

            JasperReport jrepoReport = JasperCompileManager.compileReport(jdesDesign);
            JasperPrint jprint = JasperFillManager.fillReport(jrepoReport, null,con);

            JasperViewer.viewReport(jprint,false);
            /*
            JasperDesign jdesign = JRXmlLoader.load("E:\\Java Projects\\Hotel_Manager\\src\\reportBill_internal.jrxml");
            JasperReport ireport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(ireport, null,)*/
            
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }   
       
       
       //CLEAR TABLE
       try
            {
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                Statement st1=con.createStatement();
                st.executeUpdate("delete from bill_body");
                st1.executeUpdate("delete from bill");
                
 
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Connection Error");
            }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Bill().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        homePage home=new homePage();
        home.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Bill().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtFoodNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFoodNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoodNo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCash1;
    private javax.swing.JComboBox cmbPayM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBalance1;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtCash1;
    private javax.swing.JTextField txtFoodName;
    private javax.swing.JTextField txtFoodName1;
    private javax.swing.JTextField txtFoodNo;
    private javax.swing.JTextField txtFoodNo1;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPrice1;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtQty1;
    private javax.swing.JTextField txtRoomCost;
    private javax.swing.JTextField txtRoomNo;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotal1;
    // End of variables declaration//GEN-END:variables
}
